### PR TITLE
Fix issues found by PVS-Studio static analyzer #7

### LINKED ISSUE #6: 测试 rtsp server
RestartFaultedStreams
DisconnectAndRemoveInactiveSessions
RestartFaultedStreams
DisconnectAndRemoveInactiveSessions
RestartFaultedStreams
DisconnectAndRemoveInactiveSessions 

1测试 打印这些日志   无法访问  
2  有没有demo  怎么用客服端访问  访问地址多少 
3  ffmpeg 可以推流吗

### PR DESCRIPTION
**Pull request by dimhotepus**
https://pvs-studio.com/en/order/open-source-license/

### CODE REVIEW

File: Rtsp/RtspSession.cs [hunk 1]
```diff
@@ -2131,40 +2131,37 @@ public bool ParseSessionIdAndTimeout(RtspMessage from)
                 int headerPartsLength = sessionHeaderParts.Length;
 
                 //Check if a valid value was given
-                if (headerPartsLength > 0)
+                //Trim it of whitespace
```
Comment (juliusfriedman) [inline Rtsp/RtspSession.cs:2134]: Good refactor!

File: Rtp/RtpClient.cs [hunk 2]
```diff
@@ -2291,7 +2291,8 @@ public void DisconnectSockets()
                     MulticastGroups.Clear();
 
                     //For Udp the RtcpSocket may be the same socket as the RtpSocket if the sender/reciever is duplexing
-                    if (RtcpSocket is not null && RtpSocket.Handle.Equals(RtcpSocket.Handle) is false) RtcpSocket.Close();
+                    if (RtcpSocket is not null && RtcpSocket.Handle.Equals(RtpSocket?.Handle) is false)
```
Comment (juliusfriedman) [inline Rtp/RtpClient.cs]: RtcpSocket.IsNullOrDisposed() is false, because both sockets could be disposed and this check would pass

**Comment by juliusfriedman** [comment]
I edited the file in the places where we should change the checks, The build is failing because I missed a using statement, but then I realized I should confirm with you if you want to use the long way of calling the extension or the shortway

e.g. ```socket.IsNullOrDisposed() is false``` OR ```SocketExtensions.IsNullOrDisposed(socket) is false```

Please let me know or I will fix it up asap!

Thanks again for your contributions!

**Comment by juliusfriedman** [comment]
I added the `using Media.Common.Extensions.Socket;` and kept it the short way for now. I will merge once CI completes.

Thank you!!!

**Comment by juliusfriedman** [comment]
Changes LGTM. Thanks for your contributions!
